Repository phovea/phovea_core, pull requests merged in 2019-12, with the labels that each got.

#161 Update template files and dependencies
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .yo-rc.json
  buildInfo.js
  package-lock.json
  package.json
  src/2D.ts
  src/datatype.ts
  src/internal/promise.ts
  src/iterator.ts
  src/math.ts
  src/matrix/AMatrix.ts
  src/range/Range1D.ts
  src/table/ATable.ts
  src/vector/AVector.ts
Labels: release: major, type: technical debt

#162 Change css filename from `style` to `[name]` in webpack.config.js
  webpack.config.js
Labels: release: patch, type: technical debt

#159 I18N support via phovea extension point `epPhoveaCoreLocale`
  .gitignore
  package.json
  phovea.js
  phovea_registry.js
  src/assets/locales/en/phovea.json
  src/extensions.ts
  src/i18n/index.ts
  src/phovea.ts
  src/plugin.ts
  tsconfig.json
Labels: release: minor, type: feature

#158 Add typings for login/logout extension point
  src/extensions.ts
  src/security.ts
Labels: release: patch, type: refactor
