Repository phovea/phovea_core, pull requests merged in 2020-03, with the labels that each got.

#180 Migrate to Typescript 3.8 (only)
  package.json
  src/index.ts
  src/range/Range1D.ts
  tsconfig.json
Labels: release: major, type: technical debt

#184 Update dependencies
  package.json
  src/ajax.ts
Labels: dependencies, priority: medium, type: refactor

#186 Change `buildId` to `JSON.stringify(buildId)`
  webpack.config.js
Labels: priority: medium, type: refactor

#188 Release 4.0.0
  .github/CODEOWNERS
  package.json
  src/ajax.ts
  src/index.ts
  src/range/Range1D.ts
  tsconfig.json
  webpack.config.js
Labels: release: major

#189 Migrate to Jest
  jest.config.js
  karma.conf.js
  package.json
  src/2D.ts
  src/data.ts
  src/index.ts
  src/layout.ts
  src/provenance/LocalStorageProvenanceGraphManager.ts
  src/provenance/ProvenanceGraph.ts
  tests/ajax.test.ts
  tests/geom.test.ts
  tests/index.test.ts
  tests/math.test.ts
  tests/range/Range1D.test.ts
  tests/range/index.test.ts
  tests/range/internal/RangeElem.test.ts
  tests/range/internal/SingleRangeElem.test.ts
  tests/range/internal/index.test.ts
  tests/session.test.ts
  tests/stratification.test.ts
  tests/table/table.test.ts
  tsd.d.ts
  tslint.json
  webpack.config.js
Labels: type: refactor

#177 Migrate to jest for testing
  jest.config.js
  karma.conf.js
  package.json
  src/2D.ts
  src/data.ts
  src/index.ts
  src/layout.ts
  src/provenance/LocalStorageProvenanceGraphManager.ts
  src/provenance/ProvenanceGraph.ts
  tests/ajax.test.ts
  tests/geom.test.ts
  tests/index.test.ts
  tests/math.test.ts
  tests/range/Range1D.test.ts
  tests/range/index.test.ts
  tests/range/internal/RangeElem.test.ts
  tests/range/internal/SingleRangeElem.test.ts
  tests/range/internal/index.test.ts
  tests/session.test.ts
  tests/stratification.test.ts
  tests/table/table.test.ts
  tsd.d.ts
  tslint.json
  webpack.config.js
Labels: release: major, type: refactor
