Repository phovea/phovea_core, pull requests merged in 2020-01, with the labels that each got.

#165 Specify Node.js minor version + Debian Buster in CI configs
  .circleci/config.yml
  .gitlab-ci.yml
Labels: release: patch, type: refactor

#167 Remove .travis.yml and .gitlab-ci.yml
  .gitlab-ci.yml
  .travis.yml
Labels: release: major, type: deployment

#171 Initialize a new instance of i18next instead of the default i18n…
  src/i18n/index.ts
Labels: release: minor, type: bug

#173 Release 3.1.0
  .circleci/config.yml
  .gitignore
  .gitlab-ci.yml
  .travis.yml
  package-lock.json
  package.json
  src/i18n/index.ts
  webpack.config.js
Labels: release: minor
